import {create} from 'zustand'
import {BIN_COUNT,CITY,createFillArray,makeTrucks} from '../data/model'
import type {Metrics,ScenarioEvent,ThemeMode,Truck,ViewMode,MapStyle} from '../data/types'
import {tickFill,advanceTrucks} from '../engine/sim'
import {fixedBaseline,optimize} from '../engine/routing'

const START=new Date('2026-09-16T07:00:00+05:30').getTime()
function calc(fill:Float32Array,trucks:Truck[]):Metrics{const o=optimize(fill,trucks),f=fixedBaseline(fill,trucks);const od=o.reduce((a,p)=>a+p.km,0),fd=f.reduce((a,p)=>a+p.km,0),om=o.reduce((a,p)=>a+p.minutes,0),fm=f.reduce((a,p)=>a+p.minutes,0);let critical=0,sum=0;for(let i=0;i<fill.length;i++){sum+=fill[i];if(fill[i]>=90)critical++}return{fixedKm:Number(fd.toFixed(1)),optimizedKm:Number(od.toFixed(1)),fixedMinutes:fm,optimizedMinutes:om,criticalBins:critical,overflowRiskPct:Number((sum/fill.length).toFixed(0)),fleetLoadPct:Number((trucks.reduce((a,t)=>a+t.loadKg/t.capacityKg,0)/trucks.length*100).toFixed(0)),projectedOverflow24h:Math.round(critical*1.8),activeTrucks:trucks.filter(t=>t.status!=='breakdown').length}}

interface State{view:ViewMode;mapStyle:MapStyle;theme:ThemeMode;playing:boolean;speed:number;time:number;fill:Float32Array;trucks:Truck[];events:ScenarioEvent[];history:Array<{t:number;fill:Float32Array;trucks:Truck[]}>;metrics:Metrics;selectedBin:number|null;selectedTruck:number|null;setView:(v:ViewMode)=>void;setMapStyle:(v:MapStyle)=>void;setTheme:(v:ThemeMode)=>void;togglePlaying:()=>void;setSpeed:(n:number)=>void;step:(hours:number)=>void;rewind:(hours:number)=>void;reset:()=>void;addScenario:(e:ScenarioEvent)=>void;removeScenario:(id:string)=>void;selectBin:(i:number|null)=>void;selectTruck:(i:number|null)=>void;markTruckBroken:(id:number)=>void;repairTruck:(id:number)=>void}
const initFill=createFillArray(),initTrucks=makeTrucks()
export const useTwin=create<State>((set,get)=>({view:'3d',mapStyle:'satellite',theme:'system',playing:false,speed:10,time:START,fill:initFill,trucks:initTrucks,events:[],history:[],metrics:calc(initFill,initTrucks),selectedBin:null,selectedTruck:null,setView:(view)=>set({view}),setMapStyle:(mapStyle)=>set({mapStyle}),setTheme:(theme)=>set({theme}),togglePlaying:()=>set(s=>({playing:!s.playing})),setSpeed:(speed)=>set({speed}),step:(hours)=>{const s=get(),fill=s.fill.slice(),trucks=s.trucks.map(t=>({...t,route:[...t.route]})),time=s.time+hours*3600000;tickFill(fill,s.events,time,hours);const moved=advanceTrucks(trucks,fill,hours);let plans=optimize(fill,moved);for(const p of plans){const t=moved[p.truckId];if(t)t.route=p.stops;t&&t.routeIndex===0&&(t.status=t.status==='breakdown'?'breakdown':'active')}set({time,fill,trucks:moved,metrics:calc(fill,moved),history:[...s.history,{t:time,fill:fill.slice(),trucks:moved.map(t=>({...t,route:[...t.route]}))}].slice(-13)})},rewind:(hours)=>{const s=get(),target=s.time-hours*3600000,cand=s.history.filter(h=>h.t<=target).at(-1)||s.history[0];if(!cand)return;const fill=cand.fill.slice(),trucks=cand.trucks.map(t=>({...t,route:[...t.route]}));set({time:cand.t,fill,trucks,metrics:calc(fill,trucks),history:s.history.filter(h=>h.t<=cand.t)})},reset:()=>{const fill=createFillArray(),trucks=makeTrucks();set({time:START,fill,trucks,events:[],history:[],playing:false,metrics:calc(fill,trucks),selectedBin:null,selectedTruck:null})},addScenario:(e)=>set(s=>({events:[...s.events,e]})),removeScenario:(id)=>set(s=>({events:s.events.filter(e=>e.id!==id)})),selectBin:(selectedBin)=>set({selectedBin}),selectTruck:(selectedTruck)=>set({selectedTruck}),markTruckBroken:(id)=>set(s=>({trucks:s.trucks.map(t=>t.id===id?{...t,status:'breakdown' as const,route:[]}:t),metrics:calc(s.fill,s.trucks)})),repairTruck:(id)=>set(s=>({trucks:s.trucks.map(t=>t.id===id?{...t,status:'idle' as const}:t)}))}))
export const getCityCenter=()=>CITY.center
