import type { ScenarioEvent, Truck, AuditLogItem } from '../data/types'
import { BIN_COUNT, ZONE_COUNT, binPosition, binZones, hash, zoneForLatLon, ALL_ROAD_BINS, BENGALURU_WARDS } from '../data/model'
import { getRoadRouteSync } from './osrm'

export function season(month: number) {
  if ([6, 7, 8, 9].includes(month)) return 'monsoon'
  if ([11, 12, 1, 2].includes(month)) return 'winter'
  return 'summer'
}

export function seasonMultiplier(month: number) {
  return { monsoon: 1.16, winter: 0.94, summer: 1.04 }[season(month)]
}

export function timeMultiplier(hour: number) {
  if (hour >= 6 && hour < 10) return 1.20
  if (hour >= 10 && hour < 16) return 1.04
  if (hour >= 16 && hour < 21) return 1.28
  return 0.70
}

export function humidityMultiplier(month: number) {
  return season(month) === 'monsoon' ? 1.08 : 1
}

export function eventFactor(i: number, events: ScenarioEvent[], simTime: number): number {
  if (!events || events.length === 0) return 1
  let f = 1
  const hour = simTime / 3600000
  const zone = binZones[i]

  for (const e of events) {
    const sh = e.startAt / 3600000, eh = sh + e.durationHours
    if (hour < sh || hour > eh) continue
    if (e.targetZone != null && zone !== e.targetZone) continue

    if (e.type === 'waste-surge' || e.type === 'demand-shift') f *= 1 + e.intensity * 1.5
    else if (e.type === 'overflow-risk') f *= 1 + e.intensity * 1.2
    else if (e.type === 'heavy-rain') f *= 1 + 0.5 * e.intensity
    else if (e.type === 'sensor-failure') f *= 0.8
    else if (e.type === 'combined') f *= 1 + e.intensity * 1.3
  }
  return f
}

export function tickFill(fill: Float32Array, events: ScenarioEvent[], simTime: number, deltaHours: number) {
  const date = new Date(simTime)
  const month = date.getMonth() + 1
  const hour = date.getHours() + date.getMinutes() / 60
  const sf = seasonMultiplier(month), tf = timeMultiplier(hour), hf = humidityMultiplier(month)
  const step = Math.max(0.01, Math.min(1.0, deltaHours))

  // Fast loop across 288 road-snapped bins
  for (let i = 0; i < BIN_COUNT; i++) {
    const base = 2.4 + hash(i * 5.13) * 5.5
    const zoneFactor = 1 + ((binZones[i] % ZONE_COUNT) / ZONE_COUNT) * 0.15
    const variance = 0.85 + hash(i * 1.917) * 0.30
    const ef = events.length > 0 ? eventFactor(i, events, simTime) : 1
    const nextVal = fill[i] + base * zoneFactor * variance * sf * tf * hf * ef * step
    fill[i] = nextVal > 100 ? 100 : nextVal < 0 ? 0 : nextVal
  }
}

export function visibleCriticalBins(fill: Float32Array, limit = 288): number[] {
  const ids: number[] = []
  for (let i = 0; i < fill.length; i++) {
    if (fill[i] >= 65) ids.push(i)
  }
  ids.sort((a, b) => fill[b] - fill[a])
  return ids.slice(0, limit)
}

export interface AdvanceResult {
  trucks: Truck[]
  newLogs: AuditLogItem[]
}

/**
 * Advances trucks strictly along real road geometry waypoints generated by OSRM.
 * Emits live operational audit logs explaining rerouting and dispatch rationale.
 */
export function advanceTrucks(
  trucks: Truck[],
  fill: Float32Array,
  dtHours: number,
  events: ScenarioEvent[] = [],
  simTime: number = Date.now()
): AdvanceResult {
  const next = trucks.map(t => ({
    ...t,
    route: [...t.route],
    roadPath: t.roadPath ? [...t.roadPath] : []
  }))
  const newLogs: AuditLogItem[] = []
  const timeStr = new Date(simTime).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })

  // Check active zone-level disruption modifiers
  const zoneSpeedModifiers = new Float32Array(ZONE_COUNT).fill(1.0)
  for (const e of events) {
    if (e.targetZone == null) continue
    const wName = BENGALURU_WARDS[e.targetZone]?.name || `Zone ${e.targetZone}`
    if (e.type === 'traffic-slowdown' || e.type === 'road-closure') {
      zoneSpeedModifiers[e.targetZone] = Math.max(0.2, 1 - e.intensity * 0.7)
    } else if (e.type === 'heavy-rain') {
      zoneSpeedModifiers[e.targetZone] = Math.max(0.4, 1 - e.intensity * 0.4)
    }
  }

  for (const t of next) {
    // Sanity check coordinates
    if (!Number.isFinite(t.lat) || !Number.isFinite(t.lon)) {
      t.lat = 12.9716
      t.lon = 77.5946
    }

    if (t.status === 'breakdown' || !t.route.length) continue

    // Boundary safety on routeIndex
    if (!Number.isFinite(t.routeIndex) || t.routeIndex < 0 || t.routeIndex >= t.route.length) {
      t.route = []
      t.routeIndex = 0
      t.status = 'idle'
      t.roadPath = []
      t.pathIndex = 0
      continue
    }

    const targetIndex = t.route[t.routeIndex]
    if (!Number.isFinite(targetIndex) || targetIndex < 0 || targetIndex >= BIN_COUNT) {
      t.routeIndex++
      t.roadPath = []
      t.pathIndex = 0
      continue
    }

    const targetBin = ALL_ROAD_BINS[targetIndex] || {
      lat: binPosition(targetIndex).lat,
      lon: binPosition(targetIndex).lon,
      street: 'Municipal Corridor',
      ward: 'Central Bengaluru'
    }

    // Populate road path if empty or target changed
    if (!t.roadPath || t.roadPath.length === 0) {
      const roadRoute = getRoadRouteSync({ lat: t.lat, lon: t.lon }, { lat: targetBin.lat, lon: targetBin.lon })
      t.roadPath = roadRoute.coordinates
      t.pathIndex = 0
      t.currentStreet = targetBin.street

      // Emit dispatch log
      if (Math.random() < 0.25) {
        newLogs.push({
          id: `log-${Date.now()}-${t.id}`,
          time: timeStr,
          truckName: t.name,
          zoneName: targetBin.ward,
          action: `Dispatched to ${targetBin.street}`,
          rationale: `Bin fill at ${Math.round(fill[targetIndex])}%. Road route optimized via ${roadRoute.distanceKm} km arterial corridor.`,
          type: 'reroute'
        })
      }
    }

    const truckZone = zoneForLatLon(t.lat, t.lon)
    const zoneMod = zoneSpeedModifiers[truckZone] ?? 1.0
    const kmPerHour = t.speedKph * zoneMod
    const kmToAdvance = Math.max(0.001, kmPerHour * dtHours)

    // Advance along the road waypoints
    if (t.roadPath && t.roadPath.length > 0) {
      const pIdx = t.pathIndex ?? 0
      const currentTargetPt = t.roadPath[Math.min(pIdx + 1, t.roadPath.length - 1)]

      if (currentTargetPt) {
        const destLon = currentTargetPt[0]
        const destLat = currentTargetPt[1]
        const dLat = (destLat - t.lat) * 111
        const dLon = (destLon - t.lon) * 102
        const segDist = Math.sqrt(dLat * dLat + dLon * dLon)

        if (segDist <= 0.03 || kmToAdvance >= segDist) {
          // Reached intermediate road waypoint
          t.lat = destLat
          t.lon = destLon
          t.pathIndex = (pIdx + 1)

          // If reached the final road point, we arrived at the target bin!
          if (t.pathIndex >= t.roadPath.length - 1) {
            const collected = Math.min(fill[targetIndex], Math.max(0, (t.capacityKg - t.loadKg) / 12))
            fill[targetIndex] = Math.max(0, fill[targetIndex] - collected)
            t.loadKg = Math.min(t.capacityKg, t.loadKg + collected * 12)
            t.routeIndex++
            t.roadPath = []
            t.pathIndex = 0

            newLogs.push({
              id: `log-col-${Date.now()}-${t.id}`,
              time: timeStr,
              truckName: t.name,
              zoneName: targetBin.ward,
              action: `Collected ${Math.round(collected * 12)} kg at ${targetBin.street}`,
              rationale: `Smart bin emptied from ${Math.round(fill[targetIndex] + collected)}% to ${Math.round(fill[targetIndex])}%. Vehicle at ${Math.round((t.loadKg / t.capacityKg) * 100)}% capacity.`,
              type: 'collection'
            })

            if (t.routeIndex >= t.route.length) {
              t.route = []
              t.routeIndex = 0
              t.status = t.loadKg >= t.capacityKg * 0.85 ? 'returning' : 'idle'
            } else {
              t.status = 'active'
            }
          }
        } else {
          // Advance along the road segment
          const ratio = kmToAdvance / segDist
          t.lat += (destLat - t.lat) * ratio
          t.lon += (destLon - t.lon) * ratio
        }
      }
    }
  }

  return { trucks: next, newLogs }
}
