import {useState} from 'react'
import {KeyRound,ExternalLink,Trash2,CheckCircle2,MapPinned,Box,Route,CloudSun} from 'lucide-react'
import {useProviders} from '../store/providers'
const rows=[
 {key:'googleMapsKey',name:'Google Maps Platform',cap:'Photorealistic 3D Tiles',url:'https://developers.google.com/maps/documentation/tile/get-api-key',icon:Box,note:'Requires billing; browser key can be restricted to your deployment origin.'},
 {key:'cesiumIonToken',name:'Cesium ion',cap:'World terrain / hosted assets',url:'https://ion.cesium.com/tokens',icon:Box,note:'Use a least-privilege token; limits and eligibility depend on your ion account.'},
 {key:'mapTilerKey',name:'MapTiler',cap:'Streets + satellite base maps',url:'https://cloud.maptiler.com/account/keys/',icon:MapPinned,note:'Frontend keys should be protected with provider-side restrictions.'},
 {key:'mapboxToken',name:'Mapbox',cap:'Streets + satellite base maps',url:'https://account.mapbox.com/access-tokens/',icon:MapPinned,note:'Use a public token with minimal scopes for client-side maps.'},
 {key:'stadiaKey',name:'Stadia Maps',cap:'Smooth / dark / satellite base maps',url:'https://client.stadiamaps.com/',icon:MapPinned,note:'Domain-based authentication is available for production websites.'},
 {key:'hereApiKey',name:'HERE',cap:'Optional route validation / traffic',url:'https://platform.here.com/',icon:Route,note:'Optional validation connector; core optimizer stays local.'},
 {key:'tomtomApiKey',name:'TomTom',cap:'Optional live traffic layer',url:'https://developer.tomtom.com/',icon:Route,note:'Optional traffic connector; simulation remains fully local.'},
 {key:'openRouteServiceKey',name:'openrouteservice',cap:'Optional external route validation',url:'https://openrouteservice.org/dev/#/signup',icon:Route,note:'Optional only; never required for the digital twin.'},
]
export function ProviderPanel({onClose}:{onClose:()=>void}){const p=useProviders();const [show,setShow]=useState<Record<string,boolean>>({});return <aside className="drawer provider-drawer"><div className="drawer-head"><div><div className="drawer-kicker">PROVIDER CENTER</div><h2>Power up</h2></div><button className="close-btn" onClick={onClose}>×</button></div><p className="drawer-copy">SvacchSanchar works without credentials. Provider keys stay in this browser and are used only for optional client-side capabilities.</p>{rows.map(r=>{const Icon=r.icon as any;const val=(p as any)[r.key] as string;return <div className="provider-row" key={r.key}><div className="provider-icon"><Icon size={16}/></div><div className="provider-main"><div className="provider-name">{r.name}</div><div className="provider-cap">{r.cap}</div><div className="provider-note">{r.note}</div><div className="provider-input"><input type={show[r.key]?'text':'password'} placeholder="Paste your key / token" value={val} onChange={e=>p.set(r.key as any,e.target.value)}/><button onClick={()=>setShow(s=>({...s,[r.key]:!s[r.key]}))}>{show[r.key]?'Hide':'Show'}</button><a href={r.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a></div>{val&&<div className="configured"><CheckCircle2 size={12}/> Stored locally in this browser</div>}</div></div>})}<button className="secondary-btn full danger" onClick={p.clear}><Trash2 size={15}/> Clear all provider credentials</button></aside>}
